# Assignment 4

In [1]:
import pandas as pd
import numpy as np

In [2]:
reviews = pd.read_csv("with_json_data.csv")
reviews.head()

,review_id,user_id,business_id,stars,useful,funny,cool,date,name,address,...,is_open,categories,hours,BikeParking,BusinessAcceptsCreditCards,GoodForKids,WheelchairAccessible,streetParking,BusinessAcceptsBitcoin,category_new
0,euyonIoTGp6tMa4ATcZsjQ,M0uuqU5amRW22fUCSrWiXQ,6my4VxfCGHhRIOkSjkOpAg,1,0,0,0,2020-01-01 00:06:38,Papa Murphy's,19407 South West Boones Ferry Road,...,1,"Restaurants, Pizza",NaN,False,True,True,False,False,False,Restaurants
1,FaOPA8Wg7IL9P9cRPVfg2A,IjkcZH5qcb17yn4fCc8pvg,_HjtaT4TMHwOoGG_pZmk1A,5,0,0,0,2020-01-02 20:45:16,Macho Taco,12110 Manchaca Rd,...,1,"Mexican, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '6:0-15:0', '...",False,True,True,False,False,False,Restaurants
2,f7Y_yeemyvOYPIWpF0ltZg,tCuZAr9um9rVFxR-SQwKNw,ZgoU1trH3YAVZ0378ycC-A,1,0,0,0,2020-01-04 01:11:57,Forest Ridge on Terrell Mill,1557 Terrell Mill Rd,...,1,"Apartments, Real Estate, Home Services","{'Monday': '10:0-18:0', 'Tuesday': '10:0-18:0'...",NaN,NaN,NaN,NaN,NaN,NaN,Others
3,AueHLY8Z4k4CYYHohIsdFg,USEM1lAYDJIwkGVxkSfdVw,UAtX7xmIfdd1W2Pebf6NWg,3,2,0,1,2020-01-01 19:44:49,Sidebar Boston,14 Bromfield St,...,1,"American (Traditional), Bars, Pubs, Nightlife,...","{'Monday': '11:0-1:0', 'Tuesday': '11:0-1:0', ...",True,True,True,True,True,False,Restaurants
4,eu_y7LLwOkcUi533m5SRAw,uyFAbLzaA9S56y3dVo1CIg,83_2zoVR2YmUse288HsK8g,5,0,0,0,2020-01-06 17:06:31,The Stacks Coffeehouse,1831 N Killingsworth St,...,1,"Breakfast & Brunch, Food, Restaurants, Coffee ...","{'Monday': '8:0-12:0', 'Tuesday': '8:0-12:0', ...",False,True,True,True,False,False,Restaurants

In [4]:
reviews.BikeParking.value_counts()

True     336940
False    239772
Name: BikeParking, dtype: int64

In [3]:
reviews.columns

Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'date', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'avg_stars', 'review_count', 'is_open',
       'categories', 'hours', 'BikeParking', 'BusinessAcceptsCreditCards',
       'GoodForKids', 'WheelchairAccessible', 'streetParking',
       'BusinessAcceptsBitcoin', 'category_new'],
      dtype='object')

In [5]:
len(reviews.city.unique())

648

In [6]:
reviews.loc[reviews.city == "Jamaica Plain", "longitude"] = -71.1151431
reviews.loc[reviews.city == "Jamaica Plain", "latitude"] = 42.3097365
reviews[reviews.city == "Jamaica Plain"][["longitude", "latitude"]]

        longitude   latitude
1238   -71.115143  42.309736
1302   -71.115143  42.309736
2241   -71.115143  42.309736
3898   -71.115143  42.309736
4751   -71.115143  42.309736
...           ...        ...
599301 -71.115143  42.309736
599452 -71.115143  42.309736
599540 -71.115143  42.309736
599545 -71.115143  42.309736
599743 -71.115143  42.309736

[920 rows x 2 columns]

In [9]:
reviews["category_new"] = np.nan

In [10]:
gym_rows = reviews["categories"].str.contains("gym", case=False, na=False)
restaurant_rows = reviews["categories"].str.contains("restaurant", case=False, na=False)
print(np.sum(gym_rows), np.sum(restaurant_rows))

3469 372585

In [11]:
reviews.loc[restaurant_rows, "category_new"] = "Restaurants"
reviews.loc[gym_rows, "category_new"] = "Gyms"
reviews.loc[~(restaurant_rows | gym_rows), "category_new"] = "Others"
reviews.category_new.value_counts()

Restaurants    372549
Others         224101
Gyms             3469
Name: category_new, dtype: int64

In [12]:
reviews.to_csv("with_json_data.csv", index=False)

In [13]:
reviews.shape

(600119, 27)

In [2]:
reviews = pd.read_csv("with_json_data.csv")
reviews.head()

,review_id,user_id,business_id,stars,useful,funny,cool,date,name,address,...,is_open,categories,hours,BikeParking,BusinessAcceptsCreditCards,GoodForKids,WheelchairAccessible,streetParking,BusinessAcceptsBitcoin,category_new
0,euyonIoTGp6tMa4ATcZsjQ,M0uuqU5amRW22fUCSrWiXQ,6my4VxfCGHhRIOkSjkOpAg,1,0,0,0,2020-01-01 00:06:38,Papa Murphy's,19407 South West Boones Ferry Road,...,1,"Restaurants, Pizza",NaN,False,True,True,False,False,False,Restaurants
1,FaOPA8Wg7IL9P9cRPVfg2A,IjkcZH5qcb17yn4fCc8pvg,_HjtaT4TMHwOoGG_pZmk1A,5,0,0,0,2020-01-02 20:45:16,Macho Taco,12110 Manchaca Rd,...,1,"Mexican, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '6:0-15:0', '...",False,True,True,False,False,False,Restaurants
2,f7Y_yeemyvOYPIWpF0ltZg,tCuZAr9um9rVFxR-SQwKNw,ZgoU1trH3YAVZ0378ycC-A,1,0,0,0,2020-01-04 01:11:57,Forest Ridge on Terrell Mill,1557 Terrell Mill Rd,...,1,"Apartments, Real Estate, Home Services","{'Monday': '10:0-18:0', 'Tuesday': '10:0-18:0'...",NaN,NaN,NaN,NaN,NaN,NaN,Others
3,AueHLY8Z4k4CYYHohIsdFg,USEM1lAYDJIwkGVxkSfdVw,UAtX7xmIfdd1W2Pebf6NWg,3,2,0,1,2020-01-01 19:44:49,Sidebar Boston,14 Bromfield St,...,1,"American (Traditional), Bars, Pubs, Nightlife,...","{'Monday': '11:0-1:0', 'Tuesday': '11:0-1:0', ...",True,True,True,True,True,False,Restaurants
4,eu_y7LLwOkcUi533m5SRAw,uyFAbLzaA9S56y3dVo1CIg,83_2zoVR2YmUse288HsK8g,5,0,0,0,2020-01-06 17:06:31,The Stacks Coffeehouse,1831 N Killingsworth St,...,1,"Breakfast & Brunch, Food, Restaurants, Coffee ...","{'Monday': '8:0-12:0', 'Tuesday': '8:0-12:0', ...",False,True,True,True,False,False,Restaurants

In [13]:
reviews.loc[reviews["category_new"] == "Gyms", ["state", "review_id", "stars"]].groupby("state").mean("stars")

          stars
state
BC     3.086957
CO     3.254902
FL     3.038278
GA     3.431762
MA     2.760042
OH     3.318919
OR     3.230263
TX     3.457364
WA     2.853333

In [10]:
reviews

,review_id,user_id,business_id,stars,useful,funny,cool,date,name,address,...,is_open,categories,hours,BikeParking,BusinessAcceptsCreditCards,GoodForKids,WheelchairAccessible,streetParking,BusinessAcceptsBitcoin,category_new
0,euyonIoTGp6tMa4ATcZsjQ,M0uuqU5amRW22fUCSrWiXQ,6my4VxfCGHhRIOkSjkOpAg,1,0,0,0,2020-01-01 00:06:38,Papa Murphy's,19407 South West Boones Ferry Road,...,1,"Restaurants, Pizza",NaN,False,True,True,False,False,False,Restaurants
1,FaOPA8Wg7IL9P9cRPVfg2A,IjkcZH5qcb17yn4fCc8pvg,_HjtaT4TMHwOoGG_pZmk1A,5,0,0,0,2020-01-02 20:45:16,Macho Taco,12110 Manchaca Rd,...,1,"Mexican, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '6:0-15:0', '...",False,True,True,False,False,False,Restaurants
2,f7Y_yeemyvOYPIWpF0ltZg,tCuZAr9um9rVFxR-SQwKNw,ZgoU1trH3YAVZ0378ycC-A,1,0,0,0,2020-01-04 01:11:57,Forest Ridge on Terrell Mill,1557 Terrell Mill Rd,...,1,"Apartments, Real Estate, Home Services","{'Monday': '10:0-18:0', 'Tuesday': '10:0-18:0'...",NaN,NaN,NaN,NaN,NaN,NaN,Others
3,AueHLY8Z4k4CYYHohIsdFg,USEM1lAYDJIwkGVxkSfdVw,UAtX7xmIfdd1W2Pebf6NWg,3,2,0,1,2020-01-01 19:44:49,Sidebar Boston,14 Bromfield St,...,1,"American (Traditional), Bars, Pubs, Nightlife,...","{'Monday': '11:0-1:0', 'Tuesday': '11:0-1:0', ...",True,True,True,True,True,False,Restaurants
4,eu_y7LLwOkcUi533m5SRAw,uyFAbLzaA9S56y3dVo1CIg,83_2zoVR2YmUse288HsK8g,5,0,0,0,2020-01-06 17:06:31,The Stacks Coffeehouse,1831 N Killingsworth St,...,1,"Breakfast & Brunch, Food, Restaurants, Coffee ...","{'Monday': '8:0-12:0', 'Tuesday': '8:0-12:0', ...",False,True,True,True,False,False,Restaurants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600114,D0IPxwXzxbsSf_0cfSE74w,zxzgFCdxM7bX63ZVpJgk4g,kwHcdJttuelU1TTZVDovbw,5,0,0,0,2020-12-25 09:41:16,Taste of China,"8720 NE Centerpointe Dr, Ste 101",...,1,"Restaurants, Szechuan, Cantonese, Chinese","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...",True,True,True,False,False,False,Restaurants
600115,1LrBZbLNfkBsFrHwEBlfSg,fYkURme6Piqxu4qUjQV3PQ,gEQxTJDoJYaW0l_6FYtf8g,5,1,0,0,2020-12-05 21:32:45,Mark & Toni's Coal Fired Pizza,121 Trapelo Rd,...,1,"Bars, Restaurants, Italian, Pizza, Nightlife, ...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",False,True,True,True,True,False,Restaurants
600116,F5eAqFzDEyU6q5bBuCjglg,7Ey9Xc2hC4obn7spjp1mHw,PrTS_wxKNxf0kRTOcboeIw,1,1,1,0,2020-10-23 23:28:09,Fusion Taste Fine Asian Cuisine,19 Franklin St,...,1,"Japanese, Chinese, Restaurants, Sushi Bars, As...","{'Monday': '11:30-22:0', 'Tuesday': '11:30-22:...",True,True,True,False,True,False,Restaurants
600117,7vNXRIClt-9rFzMXlrtMXA,tr13Jb83h2itjyXVwaO5eA,rbuj2X4SXIc3MDul4dcxIA,5,39,13,34,2020-06-13 02:39:26,Puddletown Bagels,8145 SE 82nd Ave,...,1,"Bagels, Breakfast & Brunch, Food, Restaurants,...","{'Monday': '7:0-15:0', 'Tuesday': '7:0-15:0', ...",True,True,True,True,True,False,Restaurants
600118,Ho57jz6U-JjrGHpGWIGLNg,HqdmRMpNvScFxjGAB40vgQ,IRzjEZ2pX4iOpnBG7oZJ7g,2,2,0,0,2020-06-22 21:54:10,Washaroo Hand Car Wash,4110 S 1st St,...,1,"Auto Detailing, Automotive, Car Wash","{'Monday': '0:0-0:0', 'Tuesday': '9:0-17:0', '...",False,True,True,False,False,False,Others